### ISSUE TITLE
Clean up JS code  in the tutorial.

### ISSUE THREAD

**Issue by kgao** [VirtualLab/virtuallab.github.io#1]
https://github.com/VirtualLab/virtuallab.github.io/commit/2a57dcc5c366306899e2a3d2d021adc2653226ba#diff-d680e8a854a7cbad6d490c445cba2ebaR212

**Comment by kgao** [comment]
https://github.com/VirtualLab/virtuallab.github.io/pull/2

**Comment by mizzao** [comment]
Thanks. For small issues like these feel free to push directly to master :)
